import cv2
import numpy as np
import logging
from typing import List, Dict, Any, Optional, Tuple

logger = logging.getLogger("veriframe.filters.scene_forensics")

class SceneForensicsAnalyzer:
    """
    Full-Scene Spatial-Temporal & Frequency Forensics Analyzer.
    Detects AI-generated video artifacts (Sora, Runway, Pika, Kling, Stable Diffusion, CGI)
    in non-face and full-scene videos using:
    1. 2D FFT Frequency-Domain Checkerboard & Spectral Harmonic Analysis
    2. Optical Flow & Motion Physics Temporal Continuity
    3. High-Pass Sensor Noise Residual (PRNU proxy) & Texture Kurtosis
    4. Inter-frame Pixel Divergence & Compression Artifact Analysis
    """

    def __init__(self):
        self.fft_size = (256, 256)

    def analyze_frequency_spectrum(self, frame: np.ndarray) -> Dict[str, float]:
        """
        Calculates 2D FFT magnitude spectrum to identify synthetic grid harmonics,
        checkerboard upsampling artifacts, and unnatural high-frequency power distribution.
        """
        try:
            if len(frame.shape) == 3:
                gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            else:
                gray = frame.copy()

            resized = cv2.resize(gray, self.fft_size, interpolation=cv2.INTER_AREA)
            
            # Compute 2D FFT and center the DC component
            f_transform = np.fft.fft2(resized.astype(np.float32))
            f_shift = np.fft.fftshift(f_transform)
            magnitude_spectrum = np.log(np.abs(f_shift) + 1e-7)

            h, w = magnitude_spectrum.shape
            center_y, center_x = h // 2, w // 2

            # Isolate high-frequency annular zone
            y_indices, x_indices = np.ogrid[:h, :w]
            dist_from_center = np.sqrt((x_indices - center_x) ** 2 + (y_indices - center_y) ** 2)
            
            high_freq_mask = (dist_from_center > (min(h, w) * 0.35)) & (dist_from_center < (min(h, w) * 0.48))
            low_freq_mask = dist_from_center < (min(h, w) * 0.20)

            high_freq_energy = float(np.mean(magnitude_spectrum[high_freq_mask])) if np.any(high_freq_mask) else 0.0
            low_freq_energy = float(np.mean(magnitude_spectrum[low_freq_mask])) if np.any(low_freq_mask) else 1.0

            ratio = high_freq_energy / max(1e-5, low_freq_energy)

            # High-frequency spectral spike count (Grid checkerboard indicator)
            high_band = magnitude_spectrum[high_freq_mask]
            q90, q10 = np.percentile(high_band, [90, 10]) if len(high_band) > 0 else (0.0, 0.0)
            peak_disparity = float(q90 - q10)

            # Synthetic images generated by diffusion/GAN upsamplers have abnormal peak disparity
            synthetic_freq_prob = float(np.clip((peak_disparity - 1.8) / 3.0, 0.0, 1.0))

            return {
                "high_low_ratio": round(ratio, 4),
                "peak_disparity": round(peak_disparity, 4),
                "frequency_synthetic_score": round(synthetic_freq_prob, 4),
            }
        except Exception as e:
            logger.debug(f"[SceneForensics] FFT analysis error: {e}")
            return {"high_low_ratio": 0.0, "peak_disparity": 0.0, "frequency_synthetic_score": 0.5}

    def analyze_motion_physics(self, frame1: np.ndarray, frame2: np.ndarray) -> Dict[str, float]:
        """
        Calculates dense Farneback optical flow to detect temporal morphing,
        unphysical motion acceleration jitter, and fluid volume distortions.
        """
        try:
            g1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY) if len(frame1.shape) == 3 else frame1
            g2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY) if len(frame2.shape) == 3 else frame2

            # Downsample for rapid dense flow computation
            small_g1 = cv2.resize(g1, (240, 135), interpolation=cv2.INTER_AREA)
            small_g2 = cv2.resize(g2, (240, 135), interpolation=cv2.INTER_AREA)

            flow = cv2.calcOpticalFlowFarneback(
                small_g1, small_g2, None,
                pyr_scale=0.5, levels=3, winsize=15, iterations=3, poly_n=5, poly_sigma=1.2, flags=0
            )

            mag, ang = cv2.cartToPolar(flow[..., 0], flow[..., 1])
            mean_mag = float(np.mean(mag))
            std_mag = float(np.std(mag))
            
            # Flow divergence (identifies unnatural local object morphing/expansion)
            fx = flow[..., 0]
            fy = flow[..., 1]
            dfx_dx = cv2.Sobel(fx, cv2.CV_32F, 1, 0, ksize=3)
            dfy_dy = cv2.Sobel(fy, cv2.CV_32F, 0, 1, ksize=3)
            divergence = np.abs(dfx_dx + dfy_dy)
            mean_div = float(np.mean(divergence))

            # AI videos tend to exhibit high divergence jitter relative to motion magnitude
            warping_index = mean_div / max(0.1, mean_mag)
            motion_synthetic_score = float(np.clip((warping_index - 0.8) / 2.0, 0.0, 1.0))

            return {
                "mean_flow_mag": round(mean_mag, 3),
                "flow_divergence": round(mean_div, 4),
                "warping_index": round(warping_index, 4),
                "motion_synthetic_score": round(motion_synthetic_score, 4),
            }
        except Exception as e:
            logger.debug(f"[SceneForensics] Optical flow error: {e}")
            return {"mean_flow_mag": 0.0, "flow_divergence": 0.0, "warping_index": 0.0, "motion_synthetic_score": 0.5}

    def analyze_noise_residual(self, frame: np.ndarray) -> Dict[str, float]:
        """
        Extracts high-pass sensor noise residual to verify the presence of
        true physical CMOS/CCD sensor PRNU pattern vs synthetic over-smoothness.
        """
        try:
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) if len(frame.shape) == 3 else frame
            blurred = cv2.GaussianBlur(gray, (5, 5), 1.0)
            residual = gray.astype(np.float32) - blurred.astype(np.float32)

            res_std = float(np.std(residual))
            # Calculate kurtosis of noise distribution
            if res_std > 1e-4:
                mean_res = float(np.mean(residual))
                m4 = float(np.mean((residual - mean_res) ** 4))
                kurtosis = m4 / (res_std ** 4)
            else:
                kurtosis = 3.0

            # Real optical sensors produce Gaussian noise (kurtosis ~ 3.0 to 6.0).
            # Generative models often have unnatural kurtosis (> 12.0 or < 1.8 due to denoising).
            kurtosis_anomaly = abs(kurtosis - 4.5)
            noise_synthetic_score = float(np.clip((kurtosis_anomaly - 2.5) / 5.0, 0.0, 1.0))

            return {
                "noise_std": round(res_std, 3),
                "noise_kurtosis": round(kurtosis, 2),
                "noise_synthetic_score": round(noise_synthetic_score, 4),
            }
        except Exception as e:
            logger.debug(f"[SceneForensics] Noise residual error: {e}")
            return {"noise_std": 0.0, "noise_kurtosis": 3.0, "noise_synthetic_score": 0.5}

    def evaluate_scene_frames(self, frames: List[np.ndarray]) -> Dict[str, Any]:
        """
        Evaluates a sequence of video scene frames across spectral, motion, and sensor noise domains.
        Returns aggregated synthetic probability, individual metric scores, and forensic observations.
        """
        if not frames:
            return {
                "scene_fake_prob": 0.5,
                "frequency_score": 0.5,
                "motion_score": 0.5,
                "noise_score": 0.5,
                "observations": ["No scene frames available for full-scene forensics."],
                "evidence": [],
            }

        freq_scores = []
        noise_scores = []
        for f in frames:
            freq_res = self.analyze_frequency_spectrum(f)
            noise_res = self.analyze_noise_residual(f)
            freq_scores.append(freq_res["frequency_synthetic_score"])
            noise_scores.append(noise_res["noise_synthetic_score"])

        motion_scores = []
        for i in range(len(frames) - 1):
            m_res = self.analyze_motion_physics(frames[i], frames[i + 1])
            motion_scores.append(m_res["motion_synthetic_score"])

        avg_freq = float(np.mean(freq_scores)) if freq_scores else 0.5
        avg_noise = float(np.mean(noise_scores)) if noise_scores else 0.5
        avg_motion = float(np.mean(motion_scores)) if motion_scores else 0.5

        # Weighted combination: 50% Spectral FFT + 35% Motion Flow + 15% Sensor Noise
        # FFT is the most reliable AI signal; Noise has high false-positive on compressed video
        aggregated_fake_prob = float(np.clip(0.50 * avg_freq + 0.35 * avg_motion + 0.15 * avg_noise, 0.0, 1.0))

        observations = [
            f"Full-Scene Forensic Analysis evaluated {len(frames)} keyframes across spectral and temporal domains.",
            f"2D FFT Frequency Grid Anomaly Index: {round(avg_freq * 100, 1)}%.",
            f"Optical Flow Temporal Warping Index: {round(avg_motion * 100, 1)}%.",
            f"Sensor Noise (PRNU) Residual Consistency: {round((1.0 - avg_noise) * 100, 1)}%.",
        ]

        evidence = []
        if aggregated_fake_prob >= 0.65:
            evidence.append("Synthetic spectral grid harmonics and generative diffusion artifacts detected.")
            if avg_motion >= 0.60:
                evidence.append("Temporal optical flow indicates unnatural object morphing and motion physics violation.")
            if avg_freq >= 0.60:
                evidence.append("High-frequency checkerboard upsampling spikes detected in 2D Fourier domain.")
        elif aggregated_fake_prob <= 0.35:
            evidence.append("Natural optical camera frequency distribution and smooth sensor noise verified.")
            evidence.append("Physical motion vectors adhere to natural momentum and camera motion continuity.")
        else:
            evidence.append("Scene forensics yielded borderline spectral and motion indicators.")

        return {
            "scene_fake_prob": round(aggregated_fake_prob, 4),
            "frequency_score": round(avg_freq, 4),
            "motion_score": round(avg_motion, 4),
            "noise_score": round(avg_noise, 4),
            "observations": observations,
            "evidence": evidence,
        }
